import { Providers } from '@/providers';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Unbounded } from 'next/font/google';

const unbounded = Unbounded({
  // variable: '--font-unbounded',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Safe Paws',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${unbounded.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
